stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: kitware/cmake:3.17
  script:
    - echo "Building project..."
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build/
    expire_in: 1 day
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - cd build
    - ctest --output-on-failure
  dependencies:
    - build_job
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'