stages:
  - build
  - test

variables:
  BUILD_DIR: build

# Trigger pipeline for merge requests
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Build stage
build:
  stage: build
  image: docker.io/conanio/gcc12:1.72.0
  script:
    - echo "Starting build process..."
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR # Save the build artifacts for later stages

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."
    - cd $BUILD_DIR
    - ctest --output-on-failure # Execute tests with detailed output
  dependencies:
    - build # Ensure the build stage is completed before running tests
