# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: gcc

stages:
  - build
  - test
  - deploy

# Build job
build:
  stage: build
  script:
    - echo "Building the application..."
    - g++ helloworld.cpp -o mybinary
  artifacts:
    paths:
      - mybinary
    expire_in: 1 week # Optional: Clean up old artifacts after a week
  cache:
    paths:
      - "*.o" # Cache object files to speed up builds
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Build on merge requests
    - if: $CI_COMMIT_BRANCH == "main" # Build on the main branch

# Test job
test:
  stage: test
  script:
    - echo "Running tests..."
    - ./runmytests.sh
  dependencies:
    - build # Use artifacts from the build job
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

# Deploy job
deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - echo "Define your deployment script here!"
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main" # Deploy only on the main branch

# Ensure pipeline success before merging
default:
  interruptible: true # Allow cancellation of jobs
  before_script:
    - echo "Setting up environment..."
  after_script:
    - echo "Cleaning up..."




